DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS associations CASCADE;
DROP TABLE IF EXISTS adoption_requests CASCADE;
DROP TABLE IF EXISTS animals CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
                       id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(100) NOT NULL,
                       surname VARCHAR(100) NOT NULL,
                       gender INT NOT NULL,
                       date_of_birth DATE NOT NULL,
                       phone_number VARCHAR(20) NOT NULL,
                       email VARCHAR(50) NOT NULL UNIQUE,
                       password VARCHAR(50) NOT NULL,
                       role INT NOT NULL DEFAULT 0,
                       address VARCHAR(255) NOT NULL
);

CREATE TABLE volunteers (
                            user_id BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
                            comment VARCHAR(255) NOT NULL,
                            status INT NOT NULL
);

CREATE TABLE associations (
                              id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                              name VARCHAR(100) NOT NULL,
                              date_of_establishment DATE NOT NULL,
                              phone_number VARCHAR(20) NOT NULL,
                              email VARCHAR(50) NOT NULL UNIQUE,
                              tip VARCHAR(100) NOT NULL,
                              description VARCHAR(255) NOT NULL,
                              address VARCHAR(255),
                              admin BIGINT REFERENCES users(id)
);

CREATE TABLE animals (
                         id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                         species VARCHAR(100) NOT NULL,
                         breed VARCHAR(100),
                         gender INT NOT NULL,
                         date_of_birth DATE,
                         description VARCHAR(255),
                         is_vacdinated INT,
                         is_sterilized INT,
                         health_status VARCHAR(255) NOT NULL,
                         date_arrived DATE NOT NULL,
                         association_id BIGINT REFERENCES associations(id) ON DELETE CASCADE
);

CREATE TABLE adoption_requests (
                                   user_id BIGINT REFERENCES users(id),
                                   animal_id BIGINT REFERENCES animals(id),
                                   status INT NOT NULL
);
