DROP TABLE IF EXISTS adoption_requests CASCADE;
DROP TABLE IF EXISTS animals CASCADE;
DROP TABLE IF EXISTS volunteers CASCADE;
DROP TABLE IF EXISTS bank_transactions CASCADE;
DROP TABLE IF EXISTS bank_accounts CASCADE;
DROP TABLE IF EXISTS associations CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name          VARCHAR(100) NOT NULL,
    surname       VARCHAR(100) NOT NULL,
    gender        INT          NOT NULL,
    date_of_birth DATE         NOT NULL,
    phone_number  VARCHAR(20)  NOT NULL,
    email         VARCHAR(50)  NOT NULL UNIQUE,
    password      VARCHAR(50)  NOT NULL,
    role          INT          NOT NULL DEFAULT 0,
    address       VARCHAR(255) NOT NULL,
    is_deleted    BOOL         NOT NULL DEFAULT FALSE
);

CREATE TABLE associations
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                  VARCHAR(100) NOT NULL,
    date_of_establishment DATE         NOT NULL,
    phone_number          VARCHAR(20)  NOT NULL,
    email                 VARCHAR(50)  NOT NULL UNIQUE,
    tip                   VARCHAR(100) NOT NULL,
    description           VARCHAR(255) NOT NULL,
    address               VARCHAR(255),
    admin                 BIGINT REFERENCES users (id),
    is_deleted            BOOL DEFAULT FALSE
);

CREATE TABLE bank_accounts
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    association_id BIGINT NOT NULL UNIQUE REFERENCES associations (id) ON DELETE CASCADE,
    account_number VARCHAR(50) NOT NULL UNIQUE,
    balance        NUMERIC(14, 2) NOT NULL DEFAULT 0 CHECK (balance >= 0)
);

CREATE TABLE bank_transactions
(
    id                  BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    bank_account_id     BIGINT NOT NULL
        REFERENCES bank_accounts (id) ON DELETE CASCADE,
    transaction_type    INT NOT NULL,
    amount              NUMERIC(14, 2) NOT NULL
        CHECK (amount > 0),
    transaction_date    DATE NOT NULL,
    source_account      VARCHAR(50) NOT NULL,
    destination_account VARCHAR(50) NOT NULL,
    purpose             VARCHAR(255) NOT NULL,
    description         VARCHAR(255)
);

CREATE TABLE volunteers
(
    user_id        BIGINT PRIMARY KEY REFERENCES users (id) ON DELETE CASCADE,
    association_id BIGINT NOT NULL REFERENCES associations (id),
    comment        VARCHAR(255) NOT NULL,
    status         INT NOT NULL
);

CREATE TABLE animals
(
    id             BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name           VARCHAR(100) NOT NULL,
    species        VARCHAR(100) NOT NULL,
    breed          VARCHAR(100),
    gender         INT          NOT NULL,
    date_of_birth  DATE,
    description    VARCHAR(255),
    is_vaccinated  INT,
    is_sterilized  INT,
    health_status  VARCHAR(255) NOT NULL,
    date_arrived   DATE         NOT NULL,
    association_id BIGINT REFERENCES associations (id) ON DELETE CASCADE,
    is_deleted     BOOL DEFAULT FALSE
);

CREATE TABLE adoption_requests
(
    user_id       BIGINT REFERENCES users (id),
    animal_id     BIGINT REFERENCES animals (id),
    status        INT NOT NULL,
    adoption_date DATE,
    request_date  DATE
);

-- Temporary adoptions: link a volunteer (user) to an animal temporarily without changing adoption status
DROP TABLE IF EXISTS temporary_adoptions CASCADE;
CREATE TABLE temporary_adoptions
(
    user_id    BIGINT REFERENCES users (id),
    animal_id  BIGINT REFERENCES animals (id),
    start_date DATE NOT NULL,
    end_date   DATE,
    PRIMARY KEY (user_id, animal_id, start_date)
);
